apiVersion: v1
kind: Namespace
metadata:
  name: user2
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: user2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: user-app:latest
        env:
        - name: USER
          value: "user2"